<div class="content-header">
	<table cellspacing="0">
        <tbody><tr>
            <td><h3 class="icon-head head-cms-page"><?php echo $this->__('Google Analytics Report') ?></h3></td>
           
        </tr>
    </tbody></table>	
	</div>
<table width="100%" border="0" cellspacing="5">
<tr>
<td colspan="2">
<div class="entry-edit">
<div class="entry-edit-head"><h4>Today</h4></div>
<fieldset>
<div id="ga_dash_historydata" class="grid">
<table width="100%" border="0" rules="all" cellpadding="5">
<tr>
<?php
$colCount=0;
foreach($this->PageVisitHistory as $key=>$val)
{
 $colCount = $colCount +1; 
?>
<td align="center">
<span style="font-size:18px; font-weight:bold;"><?php echo $val;?></span><br>
<?php echo $key;?>
</td>
<?php
 if($colCount%4==0)
  echo '</tr><tr>';
}
?>
</table>
</div>
</td>
</tr>

<tr>
<td colspan="2">
<div class="entry-edit">
<div class="entry-edit-head"><h4>Page Visits</h4></div>
<fieldset>
<div id="chart"></div>
</fieldset>
</div>
</td>
</tr>


<tr>
<td width="50%">
<div class="entry-edit">
<div class="entry-edit-head"><h4>Top Referrals</h4></div>
<fieldset>
<div id="ga_dash_rdata" style="height:425px;"></div>
</fieldset>
</div>
</td>

<td width="50%">
<div class="entry-edit">
<div class="entry-edit-head"><h4>Top Pages</h4></div>
<fieldset>
<div id="ga_dash_pgddata"></div>
</fieldset>
</div>
</td>
</tr>

<tr>
<td>
<div class="entry-edit">
<div class="entry-edit-head"><h4>Keyword Search <?php echo date('Y-m-d',strtotime('1 month ago'));?> - <?php echo date('Y-m-d');?></h4></div>
<fieldset>
<div id="ga_dash_keyworddata"></div>
</fieldset>
</div>

</td>
<td>
<div class="entry-edit">
<div class="entry-edit-head"><h4>Browser Views <?php echo date('Y-m-d',strtotime('1 month ago'));?> - <?php echo date('Y-m-d');?></h4></div>
<fieldset>
<div id="ga_dash_browserdata"></div>
</fieldset>
</div>

</td>
</tr>

<tr>
<td colspan="2">
<div id="ga_dash_mapdata"></div>
</td>
</tr>

</table>


<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">
<?php 
echo $this->topReffer;
echo $this->PageViews;
echo $this->TopPages;
//echo $this->CountryVisits;
echo $this->PageKeywordSearch;
echo $this->PageBrowserViews;
?>
</script>