<?php

class Cinasstore_Googleanalytics_Model_System_Config_Language
{
    public function toOptionArray()
    {
        $options = array(
					array('value'=>'ca_ES','label'=> Mage::helper('googleanalytics')->__('Catalan')),
					array('value'=>'cs_CZ','label'=> Mage::helper('googleanalytics')->__('Czech')),
					array('value'=>'cy_GB','label'=> Mage::helper('googleanalytics')->__('Welsh')),
					array('value'=>'da_DK','label'=> Mage::helper('googleanalytics')->__('Danish')),
					array('value'=>'de_DE','label'=> Mage::helper('googleanalytics')->__('German')),
					array('value'=>'eu_ES','label'=> Mage::helper('googleanalytics')->__('Basque')),
					array('value'=>'en_PI','label'=> Mage::helper('googleanalytics')->__('English (Pirate)')),
					array('value'=>'en_UD','label'=> Mage::helper('googleanalytics')->__('English (Upside Down)')),
					array('value'=>'ck_US','label'=> Mage::helper('googleanalytics')->__('Cherokee')),
					array('value'=>'en_US','label'=> Mage::helper('googleanalytics')->__('English (US)')),
					array('value'=>'es_LA','label'=> Mage::helper('googleanalytics')->__('Spanish')),
					array('value'=>'es_CL','label'=> Mage::helper('googleanalytics')->__('Spanish (Chile)')),
					array('value'=>'es_CO','label'=> Mage::helper('googleanalytics')->__('Spanish (Colombia)')),
					array('value'=>'es_ES','label'=> Mage::helper('googleanalytics')->__('Spanish (Spain)')),
					array('value'=>'es_MX','label'=> Mage::helper('googleanalytics')->__('Spanish (Mexico)')),
					array('value'=>'es_VE','label'=> Mage::helper('googleanalytics')->__('Spanish (Venezuela)')),
					array('value'=>'fb_FI','label'=> Mage::helper('googleanalytics')->__('Finnish (test)')),
					array('value'=>'fi_FI','label'=> Mage::helper('googleanalytics')->__('Finnish')),
					array('value'=>'fr_FR','label'=> Mage::helper('googleanalytics')->__('French (France)')),
					array('value'=>'gl_ES','label'=> Mage::helper('googleanalytics')->__('Galician')),
					array('value'=>'hu_HU','label'=> Mage::helper('googleanalytics')->__('Hungarian')),
					array('value'=>'it_IT','label'=> Mage::helper('googleanalytics')->__('Italian')),
					array('value'=>'ja_JP','label'=> Mage::helper('googleanalytics')->__('Japanese')),
					array('value'=>'ko_KR','label'=> Mage::helper('googleanalytics')->__('Korean')),
					array('value'=>'nb_NO','label'=> Mage::helper('googleanalytics')->__('Norwegian (bokmal)')),
					array('value'=>'nn_NO','label'=> Mage::helper('googleanalytics')->__('Norwegian (nynorsk)')),
					array('value'=>'nl_NL','label'=> Mage::helper('googleanalytics')->__('Dutch')),
					array('value'=>'pl_PL','label'=> Mage::helper('googleanalytics')->__('Polish')),
					array('value'=>'pt_BR','label'=> Mage::helper('googleanalytics')->__('Portuguese (Brazil)')),
					array('value'=>'pt_PT','label'=> Mage::helper('googleanalytics')->__('Portuguese (Portugal)')),
					array('value'=>'ro_RO','label'=> Mage::helper('googleanalytics')->__('Romanian')),
					array('value'=>'ru_RU','label'=> Mage::helper('googleanalytics')->__('Russian')),
					array('value'=>'sk_SK','label'=> Mage::helper('googleanalytics')->__('Slovak')),
					array('value'=>'sl_SI','label'=> Mage::helper('googleanalytics')->__('Slovenian')),
					array('value'=>'sv_SE','label'=> Mage::helper('googleanalytics')->__('Swedish')),
					array('value'=>'th_TH','label'=> Mage::helper('googleanalytics')->__('Thai')),
					array('value'=>'ku_TR','label'=> Mage::helper('googleanalytics')->__('Kurdish')),
					array('value'=>'zh_CN','label'=> Mage::helper('googleanalytics')->__('Simplified Chinese (China)')),
					array('value'=>'zh_HK','label'=> Mage::helper('googleanalytics')->__('Traditional Chinese (Hong Kong)')),
					array('value'=>'zh_TW','label'=> Mage::helper('googleanalytics')->__('Traditional Chinese (Taiwan)')),
					array('value'=>'fb_LT','label'=> Mage::helper('googleanalytics')->__('Leet Speak')),
					array('value'=>'af_ZA','label'=> Mage::helper('googleanalytics')->__('Afrikaans')),
					array('value'=>'sq_AL','label'=> Mage::helper('googleanalytics')->__('Albanian')),
					array('value'=>'hy_AM','label'=> Mage::helper('googleanalytics')->__('Armenian')),
					array('value'=>'az_AZ','label'=> Mage::helper('googleanalytics')->__('Azeri')),
					array('value'=>'be_BY','label'=> Mage::helper('googleanalytics')->__('Belarusian')),
					array('value'=>'bn_IN','label'=> Mage::helper('googleanalytics')->__('Bengali')),
					array('value'=>'bs_BA','label'=> Mage::helper('googleanalytics')->__('Bosnian')),
					array('value'=>'bg_BG','label'=> Mage::helper('googleanalytics')->__('Bulgarian')),
					array('value'=>'hr_HR','label'=> Mage::helper('googleanalytics')->__('Croatian')),
					array('value'=>'nl_BE','label'=> Mage::helper('googleanalytics')->__('Dutch (Belgie)')),
					array('value'=>'en_GB','label'=> Mage::helper('googleanalytics')->__('English (UK)')),
					array('value'=>'eo_EO','label'=> Mage::helper('googleanalytics')->__('Esperanto')),
					array('value'=>'et_EE','label'=> Mage::helper('googleanalytics')->__('Estonian')),
					array('value'=>'fo_FO','label'=> Mage::helper('googleanalytics')->__('Faroese')),
					array('value'=>'fr_CA','label'=> Mage::helper('googleanalytics')->__('French (Canada)')),
					array('value'=>'ka_GE','label'=> Mage::helper('googleanalytics')->__('Georgian')),
					array('value'=>'el_GR','label'=> Mage::helper('googleanalytics')->__('Greek')),
					array('value'=>'gu_IN','label'=> Mage::helper('googleanalytics')->__('Gujarati')),
					array('value'=>'hi_IN','label'=> Mage::helper('googleanalytics')->__('Hindi')),
					array('value'=>'is_IS','label'=> Mage::helper('googleanalytics')->__('Icelandic')),
					array('value'=>'id_ID','label'=> Mage::helper('googleanalytics')->__('Indonesian')),
					array('value'=>'ga_IE','label'=> Mage::helper('googleanalytics')->__('Irish')),
					array('value'=>'jv_ID','label'=> Mage::helper('googleanalytics')->__('Javanese')),
					array('value'=>'kn_IN','label'=> Mage::helper('googleanalytics')->__('Kannada')),
					array('value'=>'kk_KZ','label'=> Mage::helper('googleanalytics')->__('Kazakh')),
					array('value'=>'la_VA','label'=> Mage::helper('googleanalytics')->__('Latin')),
					array('value'=>'lv_LV','label'=> Mage::helper('googleanalytics')->__('Latvian')),
					array('value'=>'li_NL','label'=> Mage::helper('googleanalytics')->__('Limburgish')),
					array('value'=>'lt_LT','label'=> Mage::helper('googleanalytics')->__('Lithuanian')),
					array('value'=>'mk_MK','label'=> Mage::helper('googleanalytics')->__('Macedonian')),
					array('value'=>'mg_MG','label'=> Mage::helper('googleanalytics')->__('Malagasy')),
					array('value'=>'ms_MY','label'=> Mage::helper('googleanalytics')->__('Malay')),
					array('value'=>'mt_MT','label'=> Mage::helper('googleanalytics')->__('Maltese')),
					array('value'=>'mr_IN','label'=> Mage::helper('googleanalytics')->__('Marathi')),
					array('value'=>'mn_MN','label'=> Mage::helper('googleanalytics')->__('Mongolian')),
					array('value'=>'ne_NP','label'=> Mage::helper('googleanalytics')->__('Nepali')),
					array('value'=>'pa_IN','label'=> Mage::helper('googleanalytics')->__('Punjabi')),
					array('value'=>'rm_CH','label'=> Mage::helper('googleanalytics')->__('Romansh')),
					array('value'=>'sa_IN','label'=> Mage::helper('googleanalytics')->__('Sanskrit')),
					array('value'=>'sr_RS','label'=> Mage::helper('googleanalytics')->__('Serbian')),
					array('value'=>'so_SO','label'=> Mage::helper('googleanalytics')->__('Somali')),
					array('value'=>'sw_KE','label'=> Mage::helper('googleanalytics')->__('Swahili')),
					array('value'=>'tl_PH','label'=> Mage::helper('googleanalytics')->__('Filipino')),
					array('value'=>'ta_IN','label'=> Mage::helper('googleanalytics')->__('Tamil')),
					array('value'=>'tt_RU','label'=> Mage::helper('googleanalytics')->__('Tatar')),
					array('value'=>'te_IN','label'=> Mage::helper('googleanalytics')->__('Telugu')),
					array('value'=>'ml_IN','label'=> Mage::helper('googleanalytics')->__('Malayalam')),
					array('value'=>'uk_UA','label'=> Mage::helper('googleanalytics')->__('Ukrainian')),
					array('value'=>'uz_UZ','label'=> Mage::helper('googleanalytics')->__('Uzbek')),
					array('value'=>'vi_VN','label'=> Mage::helper('googleanalytics')->__('Vietnamese')),
					array('value'=>'xh_ZA','label'=> Mage::helper('googleanalytics')->__('Xhosa')),
					array('value'=>'zu_ZA','label'=> Mage::helper('googleanalytics')->__('Zulu')),
					array('value'=>'km_KH','label'=> Mage::helper('googleanalytics')->__('Khmer')),
					array('value'=>'tg_TJ','label'=> Mage::helper('googleanalytics')->__('Tajik')),
					array('value'=>'ar_AR','label'=> Mage::helper('googleanalytics')->__('Arabic')),
					array('value'=>'he_IL','label'=> Mage::helper('googleanalytics')->__('Hebrew')),
					array('value'=>'ur_PK','label'=> Mage::helper('googleanalytics')->__('Urdu')),
					array('value'=>'fa_IR','label'=> Mage::helper('googleanalytics')->__('Persian')),
					array('value'=>'sy_SY','label'=> Mage::helper('googleanalytics')->__('Syriac')),
					array('value'=>'yi_DE','label'=> Mage::helper('googleanalytics')->__('Yiddish')),
					array('value'=>'gn_PY','label'=> Mage::helper('googleanalytics')->__('Guarani')),
					array('value'=>'qu_PE','label'=> Mage::helper('googleanalytics')->__('Quechua')),
					array('value'=>'ay_BO','label'=> Mage::helper('googleanalytics')->__('Aymara')),
					array('value'=>'se_NO','label'=> Mage::helper('googleanalytics')->__('Northern Sami')),
					array('value'=>'ps_AF','label'=> Mage::helper('googleanalytics')->__('Pashto')),
					array('value'=>'tl_ST','label'=> Mage::helper('googleanalytics')->__('Klingon')),
				);
		return $options;
    }
}